### ISSUE TITLE
Bug no Menu superior

### ISSUE THREAD

**Issue by ussenedev** [unilicungo/informatica#3]
Notei que no menu superior tem uma aba de **Habilitações** mas quando clicado não da nenhum efeito.

Veja a imagem:

![image](https://github.com/user-attachments/assets/e3f698a9-8d5b-4886-b542-1f11147b8d4c)

**Comment by ussene026** [comment]
Em andamento. Em breve será corrigido!

**Comment by ussene026** [comment]
Obrigado pela observação o bug já foi corrigido.
